/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as HctRouteImport } from './routes/hct'
import { Route as HeyRouteImport } from './routes/hey'
import { Route as SellRouteImport } from './routes/sell'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as ZipRouteImport } from './routes/zip'
import { Route as CourseCourseIdRouteImport } from './routes/course.$courseId'
import { Route as ShopListingIdRouteImport } from './routes/shop.$listingId'
import { Route as UniUniIdRouteImport } from './routes/uni.$uniId'
import { Route as CourseCourseIdIndexRouteImport } from './routes/course.$courseId.index'
import { Route as CourseCourseIdExamRouteImport } from './routes/course.$courseId.exam'
import { Route as CourseCourseIdSummaryRouteImport } from './routes/course.$courseId.summary'
import { Route as CourseCourseIdLessonTopicIdRouteImport } from './routes/course.$courseId.lesson.$topicId'
import { Route as CourseCourseIdModuleModuleIdRouteImport } from './routes/course.$courseId.module.$moduleId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const HctRoute = HctRouteImport.update({
  id: '/hct',
  path: '/hct',
  getParentRoute: () => rootRouteImport,
} as any)
const HeyRoute = HeyRouteImport.update({
  id: '/hey',
  path: '/hey',
  getParentRoute: () => rootRouteImport,
} as any)
const SellRoute = SellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const ZipRoute = ZipRouteImport.update({
  id: '/zip',
  path: '/zip',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseCourseIdRoute = CourseCourseIdRouteImport.update({
  id: '/course/$courseId',
  path: '/course/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopListingIdRoute = ShopListingIdRouteImport.update({
  id: '/shop/$listingId',
  path: '/shop/$listingId',
  getParentRoute: () => rootRouteImport,
} as any)
const UniUniIdRoute = UniUniIdRouteImport.update({
  id: '/uni/$uniId',
  path: '/uni/$uniId',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseCourseIdIndexRoute = CourseCourseIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CourseCourseIdRoute,
} as any)
const CourseCourseIdExamRoute = CourseCourseIdExamRouteImport.update({
  id: '/exam',
  path: '/exam',
  getParentRoute: () => CourseCourseIdRoute,
} as any)
const CourseCourseIdSummaryRoute = CourseCourseIdSummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => CourseCourseIdRoute,
} as any)
const CourseCourseIdLessonTopicIdRoute =
  CourseCourseIdLessonTopicIdRouteImport.update({
    id: '/lesson/$topicId',
    path: '/lesson/$topicId',
    getParentRoute: () => CourseCourseIdRoute,
  } as any)
const CourseCourseIdModuleModuleIdRoute =
  CourseCourseIdModuleModuleIdRouteImport.update({
    id: '/module/$moduleId',
    path: '/module/$moduleId',
    getParentRoute: () => CourseCourseIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/hct': typeof HctRoute
  '/hey': typeof HeyRoute
  '/sell': typeof SellRoute
  '/staff': typeof StaffRoute
  '/zip': typeof ZipRoute
  '/course/$courseId': typeof CourseCourseIdRouteWithChildren
  '/shop/$listingId': typeof ShopListingIdRoute
  '/uni/$uniId': typeof UniUniIdRoute
  '/course/$courseId/exam': typeof CourseCourseIdExamRoute
  '/course/$courseId/summary': typeof CourseCourseIdSummaryRoute
  '/course/$courseId/': typeof CourseCourseIdIndexRoute
  '/course/$courseId/lesson/$topicId': typeof CourseCourseIdLessonTopicIdRoute
  '/course/$courseId/module/$moduleId': typeof CourseCourseIdModuleModuleIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/hct': typeof HctRoute
  '/hey': typeof HeyRoute
  '/sell': typeof SellRoute
  '/staff': typeof StaffRoute
  '/zip': typeof ZipRoute
  '/shop/$listingId': typeof ShopListingIdRoute
  '/uni/$uniId': typeof UniUniIdRoute
  '/course/$courseId/exam': typeof CourseCourseIdExamRoute
  '/course/$courseId/summary': typeof CourseCourseIdSummaryRoute
  '/course/$courseId': typeof CourseCourseIdIndexRoute
  '/course/$courseId/lesson/$topicId': typeof CourseCourseIdLessonTopicIdRoute
  '/course/$courseId/module/$moduleId': typeof CourseCourseIdModuleModuleIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/hct': typeof HctRoute
  '/hey': typeof HeyRoute
  '/sell': typeof SellRoute
  '/staff': typeof StaffRoute
  '/zip': typeof ZipRoute
  '/course/$courseId': typeof CourseCourseIdRouteWithChildren
  '/shop/$listingId': typeof ShopListingIdRoute
  '/uni/$uniId': typeof UniUniIdRoute
  '/course/$courseId/exam': typeof CourseCourseIdExamRoute
  '/course/$courseId/summary': typeof CourseCourseIdSummaryRoute
  '/course/$courseId/': typeof CourseCourseIdIndexRoute
  '/course/$courseId/lesson/$topicId': typeof CourseCourseIdLessonTopicIdRoute
  '/course/$courseId/module/$moduleId': typeof CourseCourseIdModuleModuleIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/hct'
    | '/hey'
    | '/sell'
    | '/staff'
    | '/zip'
    | '/course/$courseId'
    | '/shop/$listingId'
    | '/uni/$uniId'
    | '/course/$courseId/exam'
    | '/course/$courseId/summary'
    | '/course/$courseId/'
    | '/course/$courseId/lesson/$topicId'
    | '/course/$courseId/module/$moduleId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/hct'
    | '/hey'
    | '/sell'
    | '/staff'
    | '/zip'
    | '/shop/$listingId'
    | '/uni/$uniId'
    | '/course/$courseId/exam'
    | '/course/$courseId/summary'
    | '/course/$courseId'
    | '/course/$courseId/lesson/$topicId'
    | '/course/$courseId/module/$moduleId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/hct'
    | '/hey'
    | '/sell'
    | '/staff'
    | '/zip'
    | '/course/$courseId'
    | '/shop/$listingId'
    | '/uni/$uniId'
    | '/course/$courseId/exam'
    | '/course/$courseId/summary'
    | '/course/$courseId/'
    | '/course/$courseId/lesson/$topicId'
    | '/course/$courseId/module/$moduleId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  HctRoute: typeof HctRoute
  HeyRoute: typeof HeyRoute
  SellRoute: typeof SellRoute
  StaffRoute: typeof StaffRoute
  ZipRoute: typeof ZipRoute
  CourseCourseIdRoute: typeof CourseCourseIdRouteWithChildren
  ShopListingIdRoute: typeof ShopListingIdRoute
  UniUniIdRoute: typeof UniUniIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hct': {
      id: '/hct'
      path: '/hct'
      fullPath: '/hct'
      preLoaderRoute: typeof HctRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hey': {
      id: '/hey'
      path: '/hey'
      fullPath: '/hey'
      preLoaderRoute: typeof HeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell': {
      id: '/sell'
      path: '/sell'
      fullPath: '/sell'
      preLoaderRoute: typeof SellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zip': {
      id: '/zip'
      path: '/zip'
      fullPath: '/zip'
      preLoaderRoute: typeof ZipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course/$courseId': {
      id: '/course/$courseId'
      path: '/course/$courseId'
      fullPath: '/course/$courseId'
      preLoaderRoute: typeof CourseCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$listingId': {
      id: '/shop/$listingId'
      path: '/shop/$listingId'
      fullPath: '/shop/$listingId'
      preLoaderRoute: typeof ShopListingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uni/$uniId': {
      id: '/uni/$uniId'
      path: '/uni/$uniId'
      fullPath: '/uni/$uniId'
      preLoaderRoute: typeof UniUniIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course/$courseId/': {
      id: '/course/$courseId/'
      path: '/'
      fullPath: '/course/$courseId/'
      preLoaderRoute: typeof CourseCourseIdIndexRouteImport
      parentRoute: typeof CourseCourseIdRoute
    }
    '/course/$courseId/exam': {
      id: '/course/$courseId/exam'
      path: '/exam'
      fullPath: '/course/$courseId/exam'
      preLoaderRoute: typeof CourseCourseIdExamRouteImport
      parentRoute: typeof CourseCourseIdRoute
    }
    '/course/$courseId/summary': {
      id: '/course/$courseId/summary'
      path: '/summary'
      fullPath: '/course/$courseId/summary'
      preLoaderRoute: typeof CourseCourseIdSummaryRouteImport
      parentRoute: typeof CourseCourseIdRoute
    }
    '/course/$courseId/lesson/$topicId': {
      id: '/course/$courseId/lesson/$topicId'
      path: '/lesson/$topicId'
      fullPath: '/course/$courseId/lesson/$topicId'
      preLoaderRoute: typeof CourseCourseIdLessonTopicIdRouteImport
      parentRoute: typeof CourseCourseIdRoute
    }
    '/course/$courseId/module/$moduleId': {
      id: '/course/$courseId/module/$moduleId'
      path: '/module/$moduleId'
      fullPath: '/course/$courseId/module/$moduleId'
      preLoaderRoute: typeof CourseCourseIdModuleModuleIdRouteImport
      parentRoute: typeof CourseCourseIdRoute
    }
  }
}

interface CourseCourseIdRouteChildren {
  CourseCourseIdExamRoute: typeof CourseCourseIdExamRoute
  CourseCourseIdSummaryRoute: typeof CourseCourseIdSummaryRoute
  CourseCourseIdIndexRoute: typeof CourseCourseIdIndexRoute
  CourseCourseIdLessonTopicIdRoute: typeof CourseCourseIdLessonTopicIdRoute
  CourseCourseIdModuleModuleIdRoute: typeof CourseCourseIdModuleModuleIdRoute
}

const CourseCourseIdRouteChildren: CourseCourseIdRouteChildren = {
  CourseCourseIdExamRoute: CourseCourseIdExamRoute,
  CourseCourseIdSummaryRoute: CourseCourseIdSummaryRoute,
  CourseCourseIdIndexRoute: CourseCourseIdIndexRoute,
  CourseCourseIdLessonTopicIdRoute: CourseCourseIdLessonTopicIdRoute,
  CourseCourseIdModuleModuleIdRoute: CourseCourseIdModuleModuleIdRoute,
}

const CourseCourseIdRouteWithChildren = CourseCourseIdRoute._addFileChildren(
  CourseCourseIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  HctRoute: HctRoute,
  HeyRoute: HeyRoute,
  SellRoute: SellRoute,
  StaffRoute: StaffRoute,
  ZipRoute: ZipRoute,
  CourseCourseIdRoute: CourseCourseIdRouteWithChildren,
  ShopListingIdRoute: ShopListingIdRoute,
  UniUniIdRoute: UniUniIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
